modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Insane96/VulcaniteMod/issues"
license="MIT License"
[[mods]]
modId="vulcanite"
version="${file.jarVersion}"
displayName="Vulcanite"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vulcanite"
# logoFile="examplemod.png" #optional
authors="Insane96MCP & ZimonIsHim"
description='''
New Ore in the Nether, found below lava lakes.
Tools and Armor made with this ore, have special properties related to Fire, Flames and Lava.
Mod originally made by Insane96MCP.
Mod maintained by ZimonIsHim.
'''

[[dependencies.vulcanite]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vulcanite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
